Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/StringLiterals:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
